---
# tasks file for nginx
#  - name: Add epel-release repo
#    yum:
#      name: epel-release
#      state: present

  - name: "Install nginx"
    apt: 
      name: nginx
      state: latest
 
  - name: "Insert Index Page"
    template:
      src: index.html
      dest: /var/www/html/index.html

  - name: "Start NGiNX"
    service:
      name: nginx
      state: started
